import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function POST(req) {
  try {
    if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === "YOUR_GEMINI_API_KEY_HERE") {
      return NextResponse.json({ 
        message: "👋 I'm ready to help, but your **Gemini API Key** is not yet configured in the `.env` file. Please add a valid key to enable my full analysis and guidance capabilities." 
      });
    }

    const { messages, context } = await req.json();
    const { selectedInstrument, intelligenceData } = context;

    const instrumentData = intelligenceData?.instruments?.[selectedInstrument];
    const recentNews = intelligenceData?.news?.filter(n => 
      n.affected?.includes(selectedInstrument)
    ).slice(0, 5);

    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

    const systemPrompt = `
You are the "Digipedia AI Platform Guide & Trading Analyst." 
Your primary role is to guide traders by interpreting the analysis, tools, and data generated by our platform.

CORE MISSION:
- Interpret live system-generated signals (entry, SL, TP).
- Explain technical analysis (RSI, MACD, S/R) provided by the platform's intelligence module.
- Guide users on how to act on news impact analysis shown on their dashboard.
- Act as a proactive mentor, helping traders understand 'why' the platform is suggesting a certain move.

DATA YOU HAVE ACCESS TO FOR ${selectedInstrument}:
- Label: ${instrumentData?.label || selectedInstrument}
- Price: ${instrumentData?.current || "N/A"} (${instrumentData?.change >= 0 ? "+" : ""}${instrumentData?.change?.toFixed(2)}%)
- Trend: ${instrumentData?.trend || "N/A"}
- Structure: ${instrumentData?.structure || "N/A"}
- RSI: ${instrumentData?.rsi || "N/A"}
- MACD: ${JSON.stringify(instrumentData?.macd || {})}
- Support: ${instrumentData?.support?.join(", ") || "N/A"}
- Resistance: ${instrumentData?.resistance?.join(", ") || "N/A"}
- ATR: ${instrumentData?.atr || "N/A"}

ACTIVE SYSTEM SIGNAL:
${instrumentData?.signal ? JSON.stringify(instrumentData.signal) : "No active system signal generated yet."}

RECENT RELEVANT NEWS:
${recentNews?.map(n => `- [${n.impact}] ${n.title} (${n.sentiment})`).join("\n") || "No recent news for this instrument."}

CORE CAPABILITIES:
1. **Context-Aware Conversations**: You know exactly what is happening on the dashboard.
2. **Pre-Trade Risk Evaluation**: Always provide a Risk Level (Low/Moderate/High) and confidence percentage when asked about a trade.
3. **Explainable Trade Signals**: Break down signals into technical and fundamental reasons.
4. **Scenario Simulation**: Answer "What if" questions based on technical levels.
5. **Trade Optimization**: Suggest better entries, SL, and TP based on ATR and S/R.

TONE & BEHAVIOR:
- Never guarantee profit.
- Be analytical and data-driven.
- Include subtle risk disclaimers (e.g., "Trading involves risk; this is analysis, not financial advice").
- If the user asks for a trade summary, format it clearly with Direction, Entry, SL, TP1-3, Risk Level, and Confidence.

INTERACTIVE CONFIRMATION:
When summarizing a potential trade, always end with: "👉 Do you want to proceed with this setup, adjust the levels, or wait for more confirmation?"
`;

    // Format history for Gemini
    const contents = [
      { role: "user", parts: [{ text: systemPrompt }] },
      { role: "model", parts: [{ text: "Understood. I am now active as the Digipedia AI Trading Assistant, ready to analyze " + selectedInstrument + " and other instruments with institutional-grade precision." }] },
      ...messages.map(m => ({
        role: m.role === "user" ? "user" : "model",
        parts: [{ text: m.content }]
      }))
    ];

    const result = await model.generateContent({ contents });
    const response = await result.response;
    const text = response.text();

    return NextResponse.json({ message: text });
  } catch (error) {
    console.error("Chat API Error:", error);
    return NextResponse.json({ error: "Failed to generate AI response: " + error.message }, { status: 500 });
  }
}
